spring:
  datasource:
    driver-class-name: ${yml.file.datasource.driver}
    username: ${yml.file.datasource.username}
    url: ${yml.file.datasource.url}
    password: ${yml.file.datasource.password}
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
